# Site settings
title: yler's Blog
url: "http://yl2014.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  javascript vue react angular node jquery

# Your information
email: 842237798@qq.com
author: yler
#avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "http://7xrl5v.com1.z0.glb.clouddn.com/github%2Fio%2Fblogblog_pic.jpg"
profile: 搬砖中...
#twitter_username: twitter_username
github_username:  YL2014

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: yl2014-github-io  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

port: 5000
